  
version: '3'
services:
  client:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - HOST=0.0.0.0
    ports:
      - "${HTTP_PORT}:3000"
    tty: true
    entrypoint: "sh -c 'yarn start || (yarn build && yarn start)'"